// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:base_bloc_cubit_flutter/data/service/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FileAppTypeAdapter());
    registerAdapter(FileModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FileAppTypeAdapter());
    registerAdapter(FileModelAdapter());
  }
}
